source 'https://cdn.cocoapods.org/'
platform :ios, '18.0'

require_relative './node_modules/react-native/scripts/react_native_pods'
inhibit_all_warnings!
prepare_react_native_project!

target 'ReactNativePrebuild' do
  use_frameworks! :linkage => :static

  use_react_native!(
    :path => './node_modules/react-native',
    :app_path => "#{Pod::Config.instance.installation_root}/"
  )

  # 외부 라이브러리 경로 명시 (VeloLensModule의 의존성 해결을 위해 필수)
  pod 'VisionCamera', :path => './node_modules/react-native-vision-camera'
  pod 'RNReanimated', :path => './node_modules/react-native-reanimated'
  pod 'RNWorklets', :path => './node_modules/react-native-worklets-core'

  # 우리가 만든 JSI 모듈
  pod 'VeloLensModule', :path => '../velolens.podspec'
end

post_install do |installer|
  react_native_post_install(
      installer,
      './node_modules/react-native',
      :mac_catalyst_enabled => false
    )
end
