source 'https://cdn.cocoapods.org/'
platform :ios, '18.0'

require_relative './node_modules/react-native/scripts/react_native_pods'
inhibit_all_warnings!
prepare_react_native_project!

target 'ReactNativePrebuild' do
  use_frameworks! :linkage => :static

  use_react_native!(
    :path => './node_modules/react-native',
    :app_path => "#{Pod::Config.instance.installation_root}/"
  )

  # react-native-worklets-core (Margelo) - VisionCamera Frame Processors 필수
  pod 'react-native-worklets-core', :path => './node_modules/react-native-worklets-core'
  # react-native-worklets (Software Mansion) - react-native-reanimated v4 필수
  pod 'RNWorklets', :path => './node_modules/react-native-worklets'

  pod 'VisionCamera', :path => './node_modules/react-native-vision-camera'
  pod 'RNReanimated', :path => './node_modules/react-native-reanimated'

  # VeloLens 커스텀 JSI 모듈
  pod 'VeloLensModule', :path => '../velolens.podspec'
end

post_install do |installer|
  react_native_post_install(
      installer,
      './node_modules/react-native',
      :mac_catalyst_enabled => false
    )
end
